Adds info about RL recipes.
aguirre-lab/ml4c3-wiki pull request #132
Opened 2021-02-03 14:47 UTC by RogerPallares

Closes #117 

Adds info about recipes: rl_training, rl_hyperoptimize and rl_simulate.

2021-02-03 21:00 UTC, erikr requested changes
Great work Roger! This was clearly a big effort and will be super helpful for you and others in the future.

I have a few minor suggestions and questions below. Thanks!

2021-02-05 18:00 UTC, RogerPallares commented on Recipes.md
> +Updates a Q function based on a neural network the desired amount of episodes.
Yes, this is not very well written actually. May be: _The Q function is based on a neural network and trained over a desired number of episodes_. What I want to say basically is that the policy is a neural network and you can choose for how many episodes you can train it.

2021-02-05 18:01 UTC, RogerPallares commented on Recipes.md
> +1. `--save_dir`: Directory to save all outputs.
Actually you are right, I will change this arg to `--output_folder`

2021-02-05 18:03 UTC, RogerPallares commented on Recipes.md
> +11. `--save_name`: Name of saved files.
In this case it is the name you use to save the files, let's say you put `test24_400episodes`, then your policy will be: `test24_400episodes_policy.h5`, the reward: `test24_400episodes_reward.png`, etc.

2021-02-05 18:05 UTC, RogerPallares commented on Recipes.md
> +1. Observations, actions, rewards (`.npy` file) and parameters (`.pkl` file) over all the simulation (only if `--save` argument is set).
Maybe better if I say: Evolution of observations, actions, rewards and parameters over all the simulation?
How would you say that this output is the evolution of these elements simulated?

2021-02-05 18:12 UTC, erikr approved these changes

2021-02-05 18:12 UTC, erikr commented on Recipes.md
> +11. `--save_name`: Name of saved files.
I see, so perhaps `--result_files_prefix` is a good name?

2021-02-05 19:02 UTC, merged